apiVersion: v1
kind: Pod
metadata:
  name: hello-kubernetes
  labels:
    app: hello-kubernetes
spec:
  containers:
    - name: hello-kubernetes
      image: sammidev/hello-kubernetes:latest
      ports:
        - containerPort: 8080
      livenessProbe:
        httpGet:
          path: /healthz
          port: 8080
        initialDelaySeconds: 5
        periodSeconds: 10
      readinessProbe:
        httpGet:
          path: /ready
          port: 8080
        initialDelaySeconds: 5
        periodSeconds: 10
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
