apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
  labels:
    app: multi-container
spec:
  containers:
    - name: app-container
      image: sammidev/hello-kubernetes:latest
      ports:
        - containerPort: 8080
      livenessProbe:
        httpGet:
          path: /healthz
          port: 8080
        initialDelaySeconds: 5
        periodSeconds: 10
      readinessProbe:
        httpGet:
          path: /ready
          port: 8080
        initialDelaySeconds: 5
        periodSeconds: 10
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
    - name: proxy-container
      image: nginx:latest
      resources:
        requests:
          memory: "64Mi" # Adjust as necessary
          cpu: "250m" # Adjust as necessary
        limits:
          memory: "128Mi" # Adjust as necessary
          cpu: "500m" # Adjust as necessary
      ports:
        - containerPort: 80
      # Konfigurasi Nginx untuk meneruskan permintaan ke app-container
      volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d
  volumes:
    - name: nginx-config
      configMap:
        name: nginx-config
